version: '3.4'
services:
  db:
    image: "postgres:10.5"
    container_name: postgresDb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=chat-app-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

  chat-app-microservice:
    extends:
      file: ./chat-app-microservice/docker-compose.yml
      service: dev
    container_name: chat-app-microservice
    restart: always
    depends_on:
      - db

  frontend:
    extends:
      file: ./chat-app-frontend/docker-compose.yml
      service: dev
    container_name: chat-app-frontend

volumes:
  postgres_data: null
